/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v4.25.3
// source: src/protos/chat.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js')
const proto = require('./chat_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.ChatClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.ChatPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.protobuf.Empty,
 *   !proto.ChatMessageResponse>}
 */
const methodDescriptor_Chat_StartReceivingMessages = new grpc.web.MethodDescriptor(
  '/Chat/StartReceivingMessages',
  grpc.web.MethodType.SERVER_STREAMING,
  google_protobuf_empty_pb.Empty,
  proto.ChatMessageResponse,
  /**
   * @param {!proto.google.protobuf.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ChatMessageResponse.deserializeBinary
);


/**
 * @param {!proto.google.protobuf.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.ChatMessageResponse>}
 *     The XHR Node Readable Stream
 */
proto.ChatClient.prototype.startReceivingMessages =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/Chat/StartReceivingMessages',
      request,
      metadata || {},
      methodDescriptor_Chat_StartReceivingMessages);
};


/**
 * @param {!proto.google.protobuf.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.ChatMessageResponse>}
 *     The XHR Node Readable Stream
 */
proto.ChatPromiseClient.prototype.startReceivingMessages =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/Chat/StartReceivingMessages',
      request,
      metadata || {},
      methodDescriptor_Chat_StartReceivingMessages);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.protobuf.Empty,
 *   !proto.ChatHistory>}
 */
const methodDescriptor_Chat_JoinChat = new grpc.web.MethodDescriptor(
  '/Chat/JoinChat',
  grpc.web.MethodType.UNARY,
  google_protobuf_empty_pb.Empty,
  proto.ChatHistory,
  /**
   * @param {!proto.google.protobuf.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.ChatHistory.deserializeBinary
);


/**
 * @param {!proto.google.protobuf.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ChatHistory)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ChatHistory>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ChatClient.prototype.joinChat =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/Chat/JoinChat',
      request,
      metadata || {},
      methodDescriptor_Chat_JoinChat,
      callback);
};


/**
 * @param {!proto.google.protobuf.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ChatHistory>}
 *     Promise that resolves to the response
 */
proto.ChatPromiseClient.prototype.joinChat =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/Chat/JoinChat',
      request,
      metadata || {},
      methodDescriptor_Chat_JoinChat);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ChatMessageRequest,
 *   !proto.google.protobuf.Empty>}
 */
const methodDescriptor_Chat_SendChatMessage = new grpc.web.MethodDescriptor(
  '/Chat/SendChatMessage',
  grpc.web.MethodType.UNARY,
  proto.ChatMessageRequest,
  google_protobuf_empty_pb.Empty,
  /**
   * @param {!proto.ChatMessageRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_protobuf_empty_pb.Empty.deserializeBinary
);


/**
 * @param {!proto.ChatMessageRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.protobuf.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.protobuf.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ChatClient.prototype.sendChatMessage =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/Chat/SendChatMessage',
      request,
      metadata || {},
      methodDescriptor_Chat_SendChatMessage,
      callback);
};


/**
 * @param {!proto.ChatMessageRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.protobuf.Empty>}
 *     Promise that resolves to the response
 */
proto.ChatPromiseClient.prototype.sendChatMessage =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/Chat/SendChatMessage',
      request,
      metadata || {},
      methodDescriptor_Chat_SendChatMessage);
};


module.exports = proto;

