/**
 * @fileoverview gRPC-Web generated client stub for jwt
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v4.25.3
// source: src/protos/get_jwt.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.jwt = require('./get_jwt_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.jwt.JwtServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.jwt.JwtServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.jwt.Request,
 *   !proto.jwt.Response>}
 */
const methodDescriptor_JwtService_GetJwt = new grpc.web.MethodDescriptor(
  '/jwt.JwtService/GetJwt',
  grpc.web.MethodType.UNARY,
  proto.jwt.Request,
  proto.jwt.Response,
  /**
   * @param {!proto.jwt.Request} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.jwt.Response.deserializeBinary
);


/**
 * @param {!proto.jwt.Request} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.jwt.Response)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.jwt.Response>|undefined}
 *     The XHR Node Readable Stream
 */
proto.jwt.JwtServiceClient.prototype.getJwt =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/jwt.JwtService/GetJwt',
      request,
      metadata || {},
      methodDescriptor_JwtService_GetJwt,
      callback);
};


/**
 * @param {!proto.jwt.Request} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.jwt.Response>}
 *     Promise that resolves to the response
 */
proto.jwt.JwtServicePromiseClient.prototype.getJwt =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/jwt.JwtService/GetJwt',
      request,
      metadata || {},
      methodDescriptor_JwtService_GetJwt);
};


module.exports = proto.jwt;

